\input texinfo	@c -*-texinfo-*-

@afourpaper
@setfilename cftp.info
@settitle cftp
@setchapternewpage odd

@c ---------------------------------------------------------------------
@node   Top
@top cftp

@menu
* Functions::           Description of all bindable functions
* Index::               Index
@end menu


@include functions.texi


@c *********************************************************************
@node Index
@unnumbered Index
@cindex Index

@printindex cp

@summarycontents

@contents

@bye
